declare module '*.css';
declare module '*.svg';
declare module '*.webp';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.jsx';
declare module '*.tsx';
declare module '*';